### ISSUE TITLE
Can't compile on Arduino 1.8.13

### ISSUE THREAD

**Issue by Aleph-Design** [lorol/LITTLEFS#15]
Message is:
~/Documents/Arduino/libraries/LittleFS_esp32-1.0.5/src/LITTLEFS.h:17:10: fatal error: FS.h: No such file or directory
 #include "FS.h"
Which version do I need to compile?

**Comment by Aleph-Design** [comment]
Sorry, my bad! Have to check the correct board.

**Comment by lorol** [comment]
Alright.
Please close the case if you don't have other questions.
Thank you.
